server:
  port: 8081

spring:
  application:
    name: fun-campus-portal
  datasource:
    url: jdbc:mysql://localhost:3308/fc_portal?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: Qw020829@
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
